name: My CI/CD pipelines using github Actions

on:
  push:
    branches: main

jobs:
  builds:
      runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 
        run: | 
          echo "This is CI/CD Pipeline"
          uname -a
            


      
